#include "mpc_controller/mpc_controller.hpp"

// Treat as a system header since we don't want to touch that autogenerated stuff.
// autogenerated api
#include <acado_common.h>

#include <algorithm>
#include <limits>
#include <memory>
#include <stdexcept>
#include <string>

#include <motion_common/motion_common.hpp>
#include <time_utils/time_utils.hpp>

// extern variables in autogenerated code
ACADOworkspace acadoWorkspace;
ACADOvariables acadoVariables;

namespace motion
{
namespace control
{
namespace mpc_controller
{
/// Typedef in namespace scope instead of macro--easier for debugging
using AcadoReal = real_t;

////////////////////////////////////////////////////////////////////////////////

constexpr auto HORIZON = static_cast<std::size_t>(ACADO_N);
// State variable indices
static_assert(ACADO_NX == 6, "Unexpected num of state variables");
constexpr auto NX = static_cast<std::size_t>(ACADO_NX);
constexpr auto IDX_X = 0U;
constexpr auto IDX_Y = 1U;
constexpr auto IDX_HEADING = 2U;
constexpr auto IDX_VEL_LONG = 3U;
constexpr auto IDX_VEL_TRAN = 4U;
constexpr auto IDX_VEL_ANGULAR = 5U;
// Control variable indices
static_assert(ACADO_NU == 2, "Unexpected num of control variables");
constexpr auto NU = static_cast<std::size_t>(ACADO_NU);
constexpr auto IDX_LEFT_CMD = 0U;
constexpr auto IDX_RIGHT_CMD = 1U;

constexpr std::chrono::nanoseconds MpcController::solver_time_step;

////////////////////////////////////////////////////////////////////////////////
MpcController::MpcController(const Config & config)
: ControllerBase{config.behavior()},
  m_config{config},
  m_computed_trajectory{rosidl_runtime_cpp::MessageInitialization::ALL},
  m_last_reference_index{}
{
  if (config.do_interpolate()) {
    m_interpolated_trajectory = std::make_unique<Trajectory>();
    m_interpolated_trajectory->points.reserve(Trajectory::CAPACITY);
  }
  m_computed_trajectory.points.reserve(Trajectory::CAPACITY);
  acado_initializeSolver();
  apply_config(m_config);
}

////////////////////////////////////////////////////////////////////////////////
const Config & MpcController::get_config() const
{
  return m_config;
}

////////////////////////////////////////////////////////////////////////////////
void MpcController::set_config(const Config & config)
{
  m_config = config;
  ControllerBase::set_base_config(m_config.behavior());
  apply_config(m_config);
}

////////////////////////////////////////////////////////////////////////////////
Command MpcController::compute_command_impl(const State & state)
{
  const auto current_idx = get_current_state_temporal_index();

  auto cold_start = update_references(current_idx);
  const auto dt = x0_time_offset(state, current_idx);
  initial_conditions(predict(state.state, dt));
  {
    static_assert(sizeof(std::size_t) >= sizeof(Index), "static cast might truncate");
    // This HAS to happen after initial conditions; relies on x0 being set
    // In addition, this has to run every iteration, since there's no guarantee of
    // smoothness in the received state
    const auto max_pts = get_reference_trajectory().points.size();
    const auto horizon = std::min(static_cast<std::size_t>(max_pts - current_idx), HORIZON);
    cold_start = ensure_reference_consistency(horizon) || cold_start;
    // Consider different ways of updating initial guess for reference update
  }
  if (cold_start) {
    std::fill(&acadoVariables.u[0U], &acadoVariables.u[HORIZON * NU], AcadoReal{});
    acado_initializeNodesByForwardSimulation();
  }
  // TODO further validation on state
  solve();
  // Get result
  return interpolated_command(dt);
}

////////////////////////////////////////////////////////////////////////////////
void MpcController::solve()
{
  const auto prep_ret = acado_preparationStep();
  if (0 != prep_ret) {
    std::string err_str{"Solver preparation error: ", std::string::allocator_type{}};
    err_str += std::to_string(prep_ret);
    throw std::runtime_error{err_str};
  }
  const auto solve_ret = acado_feedbackStep();
  if (0 != solve_ret) {
    std::string err_str{"Solver error: ", std::string::allocator_type{}};
    err_str += std::to_string(solve_ret);
    throw std::runtime_error{err_str};
  }
}

////////////////////////////////////////////////////////////////////////////////
bool MpcController::update_references(const Index current_idx)
{
  const auto cold_start = Index{} == current_idx;
  // Roll forward previous solutions, references; backfill references or prune weights
  if (!cold_start) {
    const auto advance_idx = current_idx - m_last_reference_index;
    advance_problem(advance_idx);
    const auto max_pts = get_reference_trajectory().points.size();
    if (max_pts - current_idx >= HORIZON) {
      backfill_reference(advance_idx);
    } else {
      const auto receded_horizon = max_pts - current_idx;
      apply_terminal_weights(receded_horizon - 1);
      zero_nominal_weights(receded_horizon, receded_horizon + advance_idx);
      zero_terminal_weights();
    }

    // Set index *before* potential throw statements
    m_last_reference_index = current_idx;
  }
  return cold_start;
}

////////////////////////////////////////////////////////////////////////////////
void MpcController::initial_conditions(const Point & state)
{
  // Set x0
  acadoVariables.x0[IDX_X] = static_cast<AcadoReal>(state.x);
  acadoVariables.x0[IDX_Y] = static_cast<AcadoReal>(state.y);
  acadoVariables.x0[IDX_HEADING] = static_cast<AcadoReal>(motion_common::to_angle(state.heading));
  acadoVariables.x0[IDX_VEL_LONG] = static_cast<AcadoReal>(state.longitudinal_velocity_mps);
  acadoVariables.x0[IDX_VEL_TRAN] = static_cast<AcadoReal>(state.lateral_velocity_mps);
  acadoVariables.x0[IDX_VEL_ANGULAR] = static_cast<AcadoReal>(state.heading_rate_rps);
  // Initialization stuff
  acadoVariables.x[IDX_X] = acadoVariables.x0[IDX_X];
  acadoVariables.x[IDX_Y] = acadoVariables.x0[IDX_Y];
  acadoVariables.x[IDX_HEADING] = acadoVariables.x0[IDX_HEADING];
  acadoVariables.x[IDX_VEL_LONG] = acadoVariables.x0[IDX_VEL_LONG];
  acadoVariables.x[IDX_VEL_TRAN] = acadoVariables.x0[IDX_VEL_TRAN];
  acadoVariables.x[IDX_VEL_ANGULAR] = acadoVariables.x0[IDX_VEL_ANGULAR];
}

////////////////////////////////////////////////////////////////////////////////
std::chrono::nanoseconds MpcController::x0_time_offset(const State & state, Index idx)
{
  using time_utils::from_message;
  const auto & traj = get_reference_trajectory();
  // What time stamp of x0 should be
  const auto t0 =
    (from_message(traj.header.stamp) + from_message(traj.points[idx].time_from_start));
  const auto dt = t0 - from_message(state.header.stamp);
  return dt;
}

////////////////////////////////////////////////////////////////////////////////
Command MpcController::interpolated_command(const std::chrono::nanoseconds x0_time_offset)
{
  // If I roll backwards, then the actual now() time is forward
  const auto step = solver_time_step;
  auto dt_ = get_config().control_lookahead_duration() - x0_time_offset;
  const auto max_dt = step * (HORIZON - 1U);
  if (dt_ > max_dt) {
    dt_ = max_dt;
  }
  // Compute count
  // At most second from last for interpolation
  const auto count = std::min(dt_ / step, static_cast<decltype(dt_)::rep>(HORIZON - 2U));
  const auto dt = dt_ - (count * step);
  using std::chrono::duration;
  using std::chrono::duration_cast;
  const auto t = duration_cast<duration<float>>(dt) / duration_cast<duration<float>>(step);

  Command ret{rosidl_runtime_cpp::MessageInitialization::ALL};
  {
    // interpolation
    const auto idx = count * ACADO_NU;
    const auto left_cmd0 = static_cast<Real>(acadoVariables.u[idx + IDX_LEFT_CMD]);
    const auto right_cmd0 = static_cast<Real>(acadoVariables.u[idx + IDX_RIGHT_CMD]);
    const auto jdx = (count + 1U) * ACADO_NU;
    const auto left_cmd1 = static_cast<Real>(acadoVariables.u[jdx + IDX_LEFT_CMD]);
    const auto right_cmd1 = static_cast<Real>(acadoVariables.u[jdx + IDX_RIGHT_CMD]);
    ret.left_cmd = motion_common::interpolate(left_cmd0, left_cmd1, t);
    ret.right_cmd = motion_common::interpolate(right_cmd0, right_cmd1, t);
    // ret.velocity_mps = acadoVariables.x[(idx * NX) + IDX_VEL_LONG];
  }

  if (!std::isfinite(ret.left_cmd) || !std::isfinite(ret.right_cmd)) {
    throw std::runtime_error{"interpolation failed, result is not finite (NaN/Inf)"};
  }
  return ret;
}

////////////////////////////////////////////////////////////////////////////////
const MpcController::Trajectory & MpcController::get_computed_trajectory() const noexcept
{
  auto & traj = m_computed_trajectory;
  traj.header = get_reference_trajectory().header;
  traj.points.resize(HORIZON);
  for (std::size_t i = {}; i < HORIZON; ++i) {
    auto & pt = traj.points[i];
    const auto idx = NX * i;
    pt.x = static_cast<Real>(acadoVariables.x[idx + IDX_X]);
    pt.y = static_cast<Real>(acadoVariables.x[idx + IDX_Y]);
    pt.longitudinal_velocity_mps = static_cast<Real>(acadoVariables.x[idx + IDX_VEL_LONG]);
    pt.lateral_velocity_mps = static_cast<Real>(acadoVariables.x[idx + IDX_VEL_TRAN]);
    const auto heading = static_cast<Real>(acadoVariables.x[idx + IDX_HEADING]);
    pt.heading = motion_common::from_angle(heading);
    // const auto jdx = NU * i;
    // pt.acceleration_mps2 = static_cast<Real>(acadoVariables.u[jdx + IDX_JERK]);
    pt.heading_rate_rps = static_cast<Real>(acadoVariables.x[idx + IDX_VEL_ANGULAR]);
    pt.acceleration_mps2 = Real{};
  }
  return m_computed_trajectory;
}

////////////////////////////////////////////////////////////////////////////////
ControlDerivatives MpcController::get_computed_control_derivatives() const noexcept
{
  // return ControlDerivatives{
  //   static_cast<Real>(acadoVariables.u[IDX_JERK]),
  //   static_cast<Real>(acadoVariables.u[IDX_WHEEL_ANGLE_RATE])};
  return ControlDerivatives{{}, {}};
}

////////////////////////////////////////////////////////////////////////////////
void MpcController::apply_config(const Config & cfg)
{
  apply_parameters(cfg.vehicle_param(), cfg.env_forces());
  apply_bounds(cfg.limits());
  apply_weights(cfg.optimization_param());
}

////////////////////////////////////////////////////////////////////////////////
void MpcController::apply_parameters(
  const VehicleConfig & cfg, const EnvironmentForces & ef) noexcept
{
  static_assert(ACADO_NOD == 10U, "Num online parameters is not expected value!");
  for (std::size_t i = {}; i < HORIZON; ++i) {
    const auto idx = i * ACADO_NOD;
    constexpr auto idx_m1 = 0U;
    constexpr auto idx_m2 = 1U;
    constexpr auto idx_m3 = 2U;
    constexpr auto idx_d1 = 3U;
    constexpr auto idx_d2 = 4U;
    constexpr auto idx_d3 = 5U;
    constexpr auto idx_L = 6U;
    constexpr auto idx_tau_u = 7U;
    constexpr auto idx_tau_v = 8U;
    constexpr auto idx_tau_r = 9U;
    acadoVariables.od[idx + idx_m1] = static_cast<AcadoReal>(cfg.mass11());
    acadoVariables.od[idx + idx_m2] = static_cast<AcadoReal>(cfg.mass22());
    acadoVariables.od[idx + idx_m3] = static_cast<AcadoReal>(cfg.mass33());
    acadoVariables.od[idx + idx_d1] = static_cast<AcadoReal>(cfg.damping_11());
    acadoVariables.od[idx + idx_d2] = static_cast<AcadoReal>(cfg.damping_22());
    acadoVariables.od[idx + idx_d3] = static_cast<AcadoReal>(cfg.damping_33());
    acadoVariables.od[idx + idx_L] = static_cast<AcadoReal>(cfg.length_cg_thrusters_lateral_m());
    acadoVariables.od[idx + idx_tau_u] = static_cast<AcadoReal>(ef.tau_u);
    acadoVariables.od[idx + idx_tau_v] = static_cast<AcadoReal>(ef.tau_v);
    acadoVariables.od[idx + idx_tau_r] = static_cast<AcadoReal>(ef.tau_r);
  }
}
////////////////////////////////////////////////////////////////////////////////
void MpcController::apply_bounds(const LimitsConfig & cfg) noexcept
{
  static_assert(ACADO_HARDCODED_CONSTRAINT_VALUES == 0, "Constraints not hard coded");
  constexpr auto NUM_CTRL_CONSTRAINTS = 2U;
  constexpr auto NUM_STATE_CONSTRAINTS = 3U;
  for (std::size_t i = {}; i < HORIZON; ++i) {
    {
      const auto idx = i * NUM_CTRL_CONSTRAINTS;
      constexpr auto idx_left = 0U;
      constexpr auto idx_right = 1U;
      acadoVariables.lbValues[idx + idx_left] = static_cast<AcadoReal>(cfg.thruster_force().min());
      acadoVariables.ubValues[idx + idx_left] = static_cast<AcadoReal>(cfg.thruster_force().max());
      acadoVariables.lbValues[idx + idx_right] = static_cast<AcadoReal>(cfg.thruster_force().min());
      acadoVariables.ubValues[idx + idx_right] = static_cast<AcadoReal>(cfg.thruster_force().max());
    }
    {
      // DifferentialState or Affine constraints are sometimes put into different structs
      // i.e. when using qpOASES
      const auto idx = i * NUM_STATE_CONSTRAINTS;
      // These are different from the general state constraints because not all states
      // have constraints
      // If you're changing this, check the order in the code generation script
      constexpr auto idx_u = 0U;
      constexpr auto idx_v = 1U;
      constexpr auto idx_r = 2U;
      acadoVariables.lbAValues[idx + idx_u] =
        static_cast<AcadoReal>(cfg.longitudinal_velocity().min());
      acadoVariables.ubAValues[idx + idx_u] =
        static_cast<AcadoReal>(cfg.longitudinal_velocity().max());
      acadoVariables.lbAValues[idx + idx_v] = static_cast<AcadoReal>(cfg.lateral_velocity().min());
      acadoVariables.ubAValues[idx + idx_v] = static_cast<AcadoReal>(cfg.lateral_velocity().max());
      acadoVariables.lbAValues[idx + idx_r] = static_cast<AcadoReal>(cfg.yaw_rate().min());
      acadoVariables.ubAValues[idx + idx_r] = static_cast<AcadoReal>(cfg.yaw_rate().max());
    }
  }
}

////////////////////////////////////////////////////////////////////////////////
bool MpcController::check_new_trajectory(const Trajectory & trajectory) const
{
  // Check that all heading values are valid (i.e. are normalized 2D quaternions)
  if (!motion_common::heading_ok(trajectory)) {
    return false;
  }
  // If interpolating, no checks yet
  if (get_config().do_interpolate()) {
    return true;
  }
  for (Index idx = {}; idx < trajectory.points.size(); ++idx) {
    const auto & pt = trajectory.points[idx];
    // std::chrono::duration::abs is C++17
    const auto t0 = time_utils::from_message(trajectory.header.stamp);
    const auto ref = (idx * solver_time_step) + t0;
    const auto dt = get_config().sample_period_tolerance();
    const auto ub = ref + dt;
    const auto lb = ref - dt;
    const auto t = time_utils::from_message(pt.time_from_start) + t0;
    if ((t < lb) || (t > ub)) {
      return false;
    }
  }
  return true;
}

////////////////////////////////////////////////////////////////////////////////
std::string MpcController::name() const
{
  static_assert(ACADO_QP_SOLVER == ACADO_QPOASES, "QP solver backend was changed!");
  return std::string{"bicycle mpc controller qpoases", std::allocator<char>{}};
}

////////////////////////////////////////////////////////////////////////////////
Index MpcController::get_compute_iterations() const
{
  // Depends on QP solver backend; qpOASES does not expose this
  return Index{};
}
}  // namespace mpc_controller
}  // namespace control
}  // namespace motion
