/**:
  ros__parameters:
    cycle_time_ms: 100
    # Only one of the four control command topics need be specified
    # "high_level", "basic"
    control_command: "basic"
    left_thruster_usb_name: "/dev/ttyUSB0"
    right_thruster_usb_name: "/dev/ttyUSB1"
