/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mhe_autousv_ode_with_noisy_param_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};

/* mhe_autousv_ode_with_noisy_param_expl_vde_forw:(i0[6],i1[6x6],i2[6x6],i3[6],i4[9])->(o0[6],o1[6x6],o2[6x6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[4]? arg[4][0] : 0;
  a1=arg[4]? arg[4][1] : 0;
  a2=(a0+a1);
  a3=arg[0]? arg[0][3] : 0;
  a2=(a2+a3);
  a3=arg[4]? arg[4][3] : 0;
  a4=arg[0]? arg[0][1] : 0;
  a5=(a3*a4);
  a6=arg[0]? arg[0][2] : 0;
  a7=(a5*a6);
  a2=(a2+a7);
  a7=arg[4]? arg[4][5] : 0;
  a8=arg[0]? arg[0][0] : 0;
  a9=(a7*a8);
  a2=(a2-a9);
  a9=arg[4]? arg[4][2] : 0;
  a2=(a2/a9);
  a10=arg[3]? arg[3][0] : 0;
  a2=(a2+a10);
  if (res[0]!=0) res[0][0]=a2;
  a2=arg[0]? arg[0][4] : 0;
  a10=(a9*a8);
  a11=(a10*a6);
  a2=(a2-a11);
  a11=arg[4]? arg[4][6] : 0;
  a12=(a11*a4);
  a2=(a2-a12);
  a2=(a2/a3);
  a12=arg[3]? arg[3][1] : 0;
  a2=(a2+a12);
  if (res[0]!=0) res[0][1]=a2;
  a1=(a1-a0);
  a0=arg[4]? arg[4][8] : 0;
  a1=(a1*a0);
  a0=arg[0]? arg[0][5] : 0;
  a1=(a1+a0);
  a0=(a9-a3);
  a8=(a0*a8);
  a2=(a8*a4);
  a1=(a1+a2);
  a2=arg[4]? arg[4][7] : 0;
  a12=(a2*a6);
  a1=(a1-a12);
  a12=arg[4]? arg[4][4] : 0;
  a1=(a1/a12);
  a13=arg[3]? arg[3][2] : 0;
  a1=(a1+a13);
  if (res[0]!=0) res[0][2]=a1;
  a1=arg[3]? arg[3][3] : 0;
  if (res[0]!=0) res[0][3]=a1;
  a1=arg[3]? arg[3][4] : 0;
  if (res[0]!=0) res[0][4]=a1;
  a1=arg[3]? arg[3][5] : 0;
  if (res[0]!=0) res[0][5]=a1;
  a1=arg[1]? arg[1][3] : 0;
  a13=arg[1]? arg[1][1] : 0;
  a14=(a3*a13);
  a14=(a6*a14);
  a15=arg[1]? arg[1][2] : 0;
  a16=(a5*a15);
  a14=(a14+a16);
  a1=(a1+a14);
  a14=arg[1]? arg[1][0] : 0;
  a16=(a7*a14);
  a1=(a1-a16);
  a1=(a1/a9);
  if (res[1]!=0) res[1][0]=a1;
  a1=arg[1]? arg[1][4] : 0;
  a16=(a9*a14);
  a16=(a6*a16);
  a17=(a10*a15);
  a16=(a16+a17);
  a1=(a1-a16);
  a16=(a11*a13);
  a1=(a1-a16);
  a1=(a1/a3);
  if (res[1]!=0) res[1][1]=a1;
  a1=arg[1]? arg[1][5] : 0;
  a14=(a0*a14);
  a14=(a4*a14);
  a13=(a8*a13);
  a14=(a14+a13);
  a1=(a1+a14);
  a15=(a2*a15);
  a1=(a1-a15);
  a1=(a1/a12);
  if (res[1]!=0) res[1][2]=a1;
  a1=0.;
  if (res[1]!=0) res[1][3]=a1;
  if (res[1]!=0) res[1][4]=a1;
  if (res[1]!=0) res[1][5]=a1;
  a15=arg[1]? arg[1][9] : 0;
  a14=arg[1]? arg[1][7] : 0;
  a13=(a3*a14);
  a13=(a6*a13);
  a16=arg[1]? arg[1][8] : 0;
  a17=(a5*a16);
  a13=(a13+a17);
  a15=(a15+a13);
  a13=arg[1]? arg[1][6] : 0;
  a17=(a7*a13);
  a15=(a15-a17);
  a15=(a15/a9);
  if (res[1]!=0) res[1][6]=a15;
  a15=arg[1]? arg[1][10] : 0;
  a17=(a9*a13);
  a17=(a6*a17);
  a18=(a10*a16);
  a17=(a17+a18);
  a15=(a15-a17);
  a17=(a11*a14);
  a15=(a15-a17);
  a15=(a15/a3);
  if (res[1]!=0) res[1][7]=a15;
  a15=arg[1]? arg[1][11] : 0;
  a13=(a0*a13);
  a13=(a4*a13);
  a14=(a8*a14);
  a13=(a13+a14);
  a15=(a15+a13);
  a16=(a2*a16);
  a15=(a15-a16);
  a15=(a15/a12);
  if (res[1]!=0) res[1][8]=a15;
  if (res[1]!=0) res[1][9]=a1;
  if (res[1]!=0) res[1][10]=a1;
  if (res[1]!=0) res[1][11]=a1;
  a15=arg[1]? arg[1][15] : 0;
  a16=arg[1]? arg[1][13] : 0;
  a13=(a3*a16);
  a13=(a6*a13);
  a14=arg[1]? arg[1][14] : 0;
  a17=(a5*a14);
  a13=(a13+a17);
  a15=(a15+a13);
  a13=arg[1]? arg[1][12] : 0;
  a17=(a7*a13);
  a15=(a15-a17);
  a15=(a15/a9);
  if (res[1]!=0) res[1][12]=a15;
  a15=arg[1]? arg[1][16] : 0;
  a17=(a9*a13);
  a17=(a6*a17);
  a18=(a10*a14);
  a17=(a17+a18);
  a15=(a15-a17);
  a17=(a11*a16);
  a15=(a15-a17);
  a15=(a15/a3);
  if (res[1]!=0) res[1][13]=a15;
  a15=arg[1]? arg[1][17] : 0;
  a13=(a0*a13);
  a13=(a4*a13);
  a16=(a8*a16);
  a13=(a13+a16);
  a15=(a15+a13);
  a14=(a2*a14);
  a15=(a15-a14);
  a15=(a15/a12);
  if (res[1]!=0) res[1][14]=a15;
  if (res[1]!=0) res[1][15]=a1;
  if (res[1]!=0) res[1][16]=a1;
  if (res[1]!=0) res[1][17]=a1;
  a15=arg[1]? arg[1][21] : 0;
  a14=arg[1]? arg[1][19] : 0;
  a13=(a3*a14);
  a13=(a6*a13);
  a16=arg[1]? arg[1][20] : 0;
  a17=(a5*a16);
  a13=(a13+a17);
  a15=(a15+a13);
  a13=arg[1]? arg[1][18] : 0;
  a17=(a7*a13);
  a15=(a15-a17);
  a15=(a15/a9);
  if (res[1]!=0) res[1][18]=a15;
  a15=arg[1]? arg[1][22] : 0;
  a17=(a9*a13);
  a17=(a6*a17);
  a18=(a10*a16);
  a17=(a17+a18);
  a15=(a15-a17);
  a17=(a11*a14);
  a15=(a15-a17);
  a15=(a15/a3);
  if (res[1]!=0) res[1][19]=a15;
  a15=arg[1]? arg[1][23] : 0;
  a13=(a0*a13);
  a13=(a4*a13);
  a14=(a8*a14);
  a13=(a13+a14);
  a15=(a15+a13);
  a16=(a2*a16);
  a15=(a15-a16);
  a15=(a15/a12);
  if (res[1]!=0) res[1][20]=a15;
  if (res[1]!=0) res[1][21]=a1;
  if (res[1]!=0) res[1][22]=a1;
  if (res[1]!=0) res[1][23]=a1;
  a15=arg[1]? arg[1][27] : 0;
  a16=arg[1]? arg[1][25] : 0;
  a13=(a3*a16);
  a13=(a6*a13);
  a14=arg[1]? arg[1][26] : 0;
  a17=(a5*a14);
  a13=(a13+a17);
  a15=(a15+a13);
  a13=arg[1]? arg[1][24] : 0;
  a17=(a7*a13);
  a15=(a15-a17);
  a15=(a15/a9);
  if (res[1]!=0) res[1][24]=a15;
  a15=arg[1]? arg[1][28] : 0;
  a17=(a9*a13);
  a17=(a6*a17);
  a18=(a10*a14);
  a17=(a17+a18);
  a15=(a15-a17);
  a17=(a11*a16);
  a15=(a15-a17);
  a15=(a15/a3);
  if (res[1]!=0) res[1][25]=a15;
  a15=arg[1]? arg[1][29] : 0;
  a13=(a0*a13);
  a13=(a4*a13);
  a16=(a8*a16);
  a13=(a13+a16);
  a15=(a15+a13);
  a14=(a2*a14);
  a15=(a15-a14);
  a15=(a15/a12);
  if (res[1]!=0) res[1][26]=a15;
  if (res[1]!=0) res[1][27]=a1;
  if (res[1]!=0) res[1][28]=a1;
  if (res[1]!=0) res[1][29]=a1;
  a15=arg[1]? arg[1][33] : 0;
  a14=arg[1]? arg[1][31] : 0;
  a13=(a3*a14);
  a13=(a6*a13);
  a16=arg[1]? arg[1][32] : 0;
  a17=(a5*a16);
  a13=(a13+a17);
  a15=(a15+a13);
  a13=arg[1]? arg[1][30] : 0;
  a17=(a7*a13);
  a15=(a15-a17);
  a15=(a15/a9);
  if (res[1]!=0) res[1][30]=a15;
  a15=arg[1]? arg[1][34] : 0;
  a17=(a9*a13);
  a17=(a6*a17);
  a18=(a10*a16);
  a17=(a17+a18);
  a15=(a15-a17);
  a17=(a11*a14);
  a15=(a15-a17);
  a15=(a15/a3);
  if (res[1]!=0) res[1][31]=a15;
  a15=arg[1]? arg[1][35] : 0;
  a13=(a0*a13);
  a13=(a4*a13);
  a14=(a8*a14);
  a13=(a13+a14);
  a15=(a15+a13);
  a16=(a2*a16);
  a15=(a15-a16);
  a15=(a15/a12);
  if (res[1]!=0) res[1][32]=a15;
  if (res[1]!=0) res[1][33]=a1;
  if (res[1]!=0) res[1][34]=a1;
  if (res[1]!=0) res[1][35]=a1;
  a15=1.;
  a16=arg[2]? arg[2][3] : 0;
  a13=arg[2]? arg[2][1] : 0;
  a14=(a3*a13);
  a14=(a6*a14);
  a17=arg[2]? arg[2][2] : 0;
  a18=(a5*a17);
  a14=(a14+a18);
  a16=(a16+a14);
  a14=arg[2]? arg[2][0] : 0;
  a18=(a7*a14);
  a16=(a16-a18);
  a16=(a16/a9);
  a16=(a15+a16);
  if (res[2]!=0) res[2][0]=a16;
  a16=arg[2]? arg[2][4] : 0;
  a18=(a9*a14);
  a18=(a6*a18);
  a19=(a10*a17);
  a18=(a18+a19);
  a16=(a16-a18);
  a18=(a11*a13);
  a16=(a16-a18);
  a16=(a16/a3);
  if (res[2]!=0) res[2][1]=a16;
  a16=arg[2]? arg[2][5] : 0;
  a14=(a0*a14);
  a14=(a4*a14);
  a13=(a8*a13);
  a14=(a14+a13);
  a16=(a16+a14);
  a17=(a2*a17);
  a16=(a16-a17);
  a16=(a16/a12);
  if (res[2]!=0) res[2][2]=a16;
  if (res[2]!=0) res[2][3]=a1;
  if (res[2]!=0) res[2][4]=a1;
  if (res[2]!=0) res[2][5]=a1;
  a16=arg[2]? arg[2][9] : 0;
  a17=arg[2]? arg[2][7] : 0;
  a14=(a3*a17);
  a14=(a6*a14);
  a13=arg[2]? arg[2][8] : 0;
  a18=(a5*a13);
  a14=(a14+a18);
  a16=(a16+a14);
  a14=arg[2]? arg[2][6] : 0;
  a18=(a7*a14);
  a16=(a16-a18);
  a16=(a16/a9);
  if (res[2]!=0) res[2][6]=a16;
  a16=arg[2]? arg[2][10] : 0;
  a18=(a9*a14);
  a18=(a6*a18);
  a19=(a10*a13);
  a18=(a18+a19);
  a16=(a16-a18);
  a18=(a11*a17);
  a16=(a16-a18);
  a16=(a16/a3);
  a16=(a15+a16);
  if (res[2]!=0) res[2][7]=a16;
  a16=arg[2]? arg[2][11] : 0;
  a14=(a0*a14);
  a14=(a4*a14);
  a17=(a8*a17);
  a14=(a14+a17);
  a16=(a16+a14);
  a13=(a2*a13);
  a16=(a16-a13);
  a16=(a16/a12);
  if (res[2]!=0) res[2][8]=a16;
  if (res[2]!=0) res[2][9]=a1;
  if (res[2]!=0) res[2][10]=a1;
  if (res[2]!=0) res[2][11]=a1;
  a16=arg[2]? arg[2][15] : 0;
  a13=arg[2]? arg[2][13] : 0;
  a14=(a3*a13);
  a14=(a6*a14);
  a17=arg[2]? arg[2][14] : 0;
  a18=(a5*a17);
  a14=(a14+a18);
  a16=(a16+a14);
  a14=arg[2]? arg[2][12] : 0;
  a18=(a7*a14);
  a16=(a16-a18);
  a16=(a16/a9);
  if (res[2]!=0) res[2][12]=a16;
  a16=arg[2]? arg[2][16] : 0;
  a18=(a9*a14);
  a18=(a6*a18);
  a19=(a10*a17);
  a18=(a18+a19);
  a16=(a16-a18);
  a18=(a11*a13);
  a16=(a16-a18);
  a16=(a16/a3);
  if (res[2]!=0) res[2][13]=a16;
  a16=arg[2]? arg[2][17] : 0;
  a14=(a0*a14);
  a14=(a4*a14);
  a13=(a8*a13);
  a14=(a14+a13);
  a16=(a16+a14);
  a17=(a2*a17);
  a16=(a16-a17);
  a16=(a16/a12);
  a16=(a15+a16);
  if (res[2]!=0) res[2][14]=a16;
  if (res[2]!=0) res[2][15]=a1;
  if (res[2]!=0) res[2][16]=a1;
  if (res[2]!=0) res[2][17]=a1;
  a16=arg[2]? arg[2][21] : 0;
  a17=arg[2]? arg[2][19] : 0;
  a14=(a3*a17);
  a14=(a6*a14);
  a13=arg[2]? arg[2][20] : 0;
  a18=(a5*a13);
  a14=(a14+a18);
  a16=(a16+a14);
  a14=arg[2]? arg[2][18] : 0;
  a18=(a7*a14);
  a16=(a16-a18);
  a16=(a16/a9);
  if (res[2]!=0) res[2][18]=a16;
  a16=arg[2]? arg[2][22] : 0;
  a18=(a9*a14);
  a18=(a6*a18);
  a19=(a10*a13);
  a18=(a18+a19);
  a16=(a16-a18);
  a18=(a11*a17);
  a16=(a16-a18);
  a16=(a16/a3);
  if (res[2]!=0) res[2][19]=a16;
  a16=arg[2]? arg[2][23] : 0;
  a14=(a0*a14);
  a14=(a4*a14);
  a17=(a8*a17);
  a14=(a14+a17);
  a16=(a16+a14);
  a13=(a2*a13);
  a16=(a16-a13);
  a16=(a16/a12);
  if (res[2]!=0) res[2][20]=a16;
  if (res[2]!=0) res[2][21]=a15;
  if (res[2]!=0) res[2][22]=a1;
  if (res[2]!=0) res[2][23]=a1;
  a16=arg[2]? arg[2][27] : 0;
  a13=arg[2]? arg[2][25] : 0;
  a14=(a3*a13);
  a14=(a6*a14);
  a17=arg[2]? arg[2][26] : 0;
  a18=(a5*a17);
  a14=(a14+a18);
  a16=(a16+a14);
  a14=arg[2]? arg[2][24] : 0;
  a18=(a7*a14);
  a16=(a16-a18);
  a16=(a16/a9);
  if (res[2]!=0) res[2][24]=a16;
  a16=arg[2]? arg[2][28] : 0;
  a18=(a9*a14);
  a18=(a6*a18);
  a19=(a10*a17);
  a18=(a18+a19);
  a16=(a16-a18);
  a18=(a11*a13);
  a16=(a16-a18);
  a16=(a16/a3);
  if (res[2]!=0) res[2][25]=a16;
  a16=arg[2]? arg[2][29] : 0;
  a14=(a0*a14);
  a14=(a4*a14);
  a13=(a8*a13);
  a14=(a14+a13);
  a16=(a16+a14);
  a17=(a2*a17);
  a16=(a16-a17);
  a16=(a16/a12);
  if (res[2]!=0) res[2][26]=a16;
  if (res[2]!=0) res[2][27]=a1;
  if (res[2]!=0) res[2][28]=a15;
  if (res[2]!=0) res[2][29]=a1;
  a16=arg[2]? arg[2][33] : 0;
  a17=arg[2]? arg[2][31] : 0;
  a14=(a3*a17);
  a14=(a6*a14);
  a13=arg[2]? arg[2][32] : 0;
  a5=(a5*a13);
  a14=(a14+a5);
  a16=(a16+a14);
  a14=arg[2]? arg[2][30] : 0;
  a7=(a7*a14);
  a16=(a16-a7);
  a16=(a16/a9);
  if (res[2]!=0) res[2][30]=a16;
  a16=arg[2]? arg[2][34] : 0;
  a9=(a9*a14);
  a6=(a6*a9);
  a10=(a10*a13);
  a6=(a6+a10);
  a16=(a16-a6);
  a11=(a11*a17);
  a16=(a16-a11);
  a16=(a16/a3);
  if (res[2]!=0) res[2][31]=a16;
  a16=arg[2]? arg[2][35] : 0;
  a0=(a0*a14);
  a4=(a4*a0);
  a8=(a8*a17);
  a4=(a4+a8);
  a16=(a16+a4);
  a2=(a2*a13);
  a16=(a16-a2);
  a16=(a16/a12);
  if (res[2]!=0) res[2][32]=a16;
  if (res[2]!=0) res[2][33]=a1;
  if (res[2]!=0) res[2][34]=a1;
  if (res[2]!=0) res[2][35]=a15;
  return 0;
}

CASADI_SYMBOL_EXPORT int mhe_autousv_ode_with_noisy_param_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mhe_autousv_ode_with_noisy_param_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mhe_autousv_ode_with_noisy_param_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mhe_autousv_ode_with_noisy_param_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mhe_autousv_ode_with_noisy_param_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mhe_autousv_ode_with_noisy_param_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mhe_autousv_ode_with_noisy_param_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void mhe_autousv_ode_with_noisy_param_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mhe_autousv_ode_with_noisy_param_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int mhe_autousv_ode_with_noisy_param_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real mhe_autousv_ode_with_noisy_param_expl_vde_forw_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mhe_autousv_ode_with_noisy_param_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mhe_autousv_ode_with_noisy_param_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mhe_autousv_ode_with_noisy_param_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mhe_autousv_ode_with_noisy_param_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mhe_autousv_ode_with_noisy_param_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
