#include "builtin_interfaces/msg/Time.idl"

module usv_msgs {
    module msg {
        @verbatim (language="comment", text="real-time estimated states and parameters")
        struct EnvEstimation {
            builtin_interfaces::msg::Time stamp;
                      
            @default (value=0.0)
            float tau_env_u;
            
            @default (value=0.0)
            float tau_env_v;
            
            @default (value=0.0)
            float tau_env_r;
        };
    };
};
