#include "builtin_interfaces/msg/Time.idl"

module usv_msgs {
  module msg {
    struct HighLevelControlCommand {
      builtin_interfaces::msg::Time stamp;

      float tau_u;

      float tau_v;
      
      float tau_r;
      
      float left_cmd;
      
      float right_cmd;
    };
  };
};
