/**:
  ros__parameters:
    costmap_frame: "map"
    vehicle_frame: "base_link"
    grid_min_value: 0.0
    grid_max_value: 1.0
    min_lidar_height_thres: -1.0
    max_lidar_height_thres: 5.0
    grid_resoultion: 0.2
    grid_length_x: 70.0
    grid_length_y: 70.0
    grid_position_x: 0.0
    grid_position_y: 0.0
